std_msgs/Header                     header
geometry_msgs/Pose                  pose
geometry_msgs/Twist                 vel
geometry_msgs/Twist                 acc
float64[]                           pose_var
float64[]                           vel_var
float64[]                           acc_var
float64                             heading
float64[]                           imu_bias
float64[]                           imu_bias_var
float64[]                           cbd
float64[]                           cbd_var
uint32[]                            amb
float64[]                           amb_var

