std_msgs/Header   header
GNSSRawHeader     gnss_header
uint32            sv_id

uint8 ROVER=0
uint8 BASESTATION=1
uint8             source

float64           ura
uint8             ura_index
uint32            health
float64           t_gd1
float64           t_gd2
uint32            aodc
uint32            z_week
float64           t_oc
float64           a_f0
float64           a_f1
float64           a_f2
uint32            aode
float64           t_oe
float64           sqrt_a
float64           ecc
float64           omega  #Argument of perigee
float64           delta_n
float64           m_0
float64           omega_0
float64           omega_dot
float64           i_0
float64           i_dot
float64           cuc
float64           cus
float64           crc
float64           crs
float64           cic
float64           cis
uint16            wnt_oe  
uint16            wnt_oc
