std_msgs/Header   header
string            solution_name

# m
float64           northing
float64           easting
float64           height
float64           northing_std
float64           easting_std
float64           height_std

# m/s
float64           vel_e
float64           vel_n
float64           vel_u
float64           vel_e_std
float64           vel_n_std
float64           vel_u_std

# angle in radian
float64           roll      
float64           pitch
float64           yaw
float64           roll_std
float64           pitch_std
float64           yaw_std